### PR TITLE
Prepare for 2.0 release

### LINKED ISSUE #7: Bifunctor instance
Hi folks, would you consider a PR for this?

### PR DESCRIPTION
**Pull request by garyb**
Resolves #7

### CODE REVIEW

**Comment by paf31** [comment]
👍  LGTM

**Comment by garyb** [comment]
I wondered if there was some trick we could use here to avoid the need for two versions of `V`, so you could choose which strategy (semiring or semigroup) to use via newtype or something, but I don't know if it's worth it?

**Comment by paf31** [comment]
I think a solution is to use the `Semiring` version and make a type synonym (and helper functions) in another module for `V (Additive s)`.

**Comment by paf31** [comment]
👍

**Pull request merged**
