### PR TITLE
Add Semigroup Validation Examples

### PR DESCRIPTION
**Pull request by jkachmar**
This is my first pass at adding a more detailed Semigroup Validation example, similar in spirit to [the examples in the Halogen repository](https://github.com/slamdata/purescript-halogen/tree/master/examples).

If this looks like something that would be valuable to have in the repo, I make a similar example for Semiring Validation and include it in this PR as well.

### CODE REVIEW

**Comment by chexxor** [comment]
Anything holding this from being merged? I don't see any problems with merging stuff into an "examples" directory - shouldn't break anything.

**Comment by chexxor** [comment]
Bump

**Comment by Profpatsch** [comment]
cc @garyb

**Comment by hdgarrood** [comment]
I'm going to try to look at this properly over the next week or so.

**Comment by jkachmar** [comment]
Hey, sorry about the lag on this. I'll try to rebuild this project with a modern version of `purs` and address your comments.

**Comment by hdgarrood** [comment]
No rush at all - it took me over a year to get around to looking at this in the first place so I can't complain :laughing:

**Comment by Profpatsch** [comment]
You can do it!

**Comment by jkachmar** [comment]
Finally got around to this (thanks Compose Unconference!). I needed to use `over2` rather than `under2`, but it seems as if your `Map.unionWith` suggestion worked just fine!

**Comment by hdgarrood** [comment]
Looks great, thanks! Would you mind adding a `build:example` script in `package.json` and having the `.travis.yml` script run it after the normal build so that CI can check that this doesn't go out of date?

**Comment by hdgarrood** [comment]
Thanks very much!

**Pull request merged**
