### PR TITLE
Add Parallel instances for Either V

### PR DESCRIPTION
**Pull request by garyb**

### CODE REVIEW

**Comment by garyb** [comment]
@natefaubion makes a good point, this shouldn't be possible as we overlapping instances now.

**Comment by paf31** [comment]
The other issue here is that the bidirectional fundeps means this is the only way that `Either` can be parallelized (globally). Actually, this is the same issue as the overlap issue, worded differently. It could be fixed by making a newtype for `Either`, but that might not be ideal either.

**Comment by paf31** [comment]
What shall we do with this? What about creating `newtype`s?

**Comment by garyb** [comment]
I don't know, what do you think? I'm fine with just abandoning it too.

**Comment by paf31** [comment]
OK, sounds good for now. We can come back to this later if we need it for anything.

**Pull request closed without merging**
